# Next bounded batch after v050

The later-event and sampled gapped connections in v048 complete that explicitly bounded task. Do not mark the full campaign complete: the preparation route and the separate lower unlink collision remain open. Preserve both historical geometry choices, name cutoff_tol, use two primary workers at most, and freeze the next protocol before its decisive runs.

1. Completed in v050: upper-pair birth near A≈0.137, both engines at N4/N6. Preserve the accepted windows; no need to rerun them before advancing item 2.
2. For the extra flat-pair birth near A≈0.17 and annihilation near B≈−0.03, **do not reuse a global positive-flat-gap criterion**: the original flat pair remains present, so that global gap is zero on both sides of the extra pair's event. Define and freeze a local domain around the candidate, away from the original roots. Require two distinct local roots, fold nondegeneracy, mesh/radius charge agreement, a positive boundary gap and a bounded local open-side minimum. Track the original pair separately. A local event does not certify a complete global inventory.
3. Resolve the lower-pair birth on B:−0.10→−0.25 by following both v044 lower-root seeds backward. v048 confirms that the one-node count at B=−0.25 is an undercount: two roots exist, separated by about 0.068. Do not infer a birth/death from global search failure. The momenta and same-state joins are in provenance/lower_inventory_probe.json.
4. Trace the original flat pair along A:0→0.2, B=T=0 and then B:0→−0.25, A=0.2, with parameter and comparison-path refinement. After the upper/lower contacts the flat two-band group is not globally isolated; local charge checks and a globally defined Euler class are different claims. Join the final roots and relative orientation explicitly to v044. The same-state root join is already established, but no absolute historical frame sign is assumed.
5. Finally resolve the separate lower unlink collision from the last accepted lower-root inventory in v044. The earlier parameter-leg replay did not measure that event itself. Identify its bracket from the retained records before assigning an event label.

Update the generated ledger only from accepted records. Keep candidate brackets, local-domain events, global sampled searches, and fully sampled parameter legs distinct. If the preparation protocol changes the event gate to a local domain, record that change explicitly instead of silently weakening the older global-gap test.
