# Opening-gate failures and separately frozen recovery

Both initial N8 workers ended in REJECT. Their fold solves, eleven root states and two opposite-charge measurements completed; neither completed an accepted opening search or measured the surviving upper pair. These original records are unchanged in results/first_ann_*_N8.json.

BM's three optimization attempts at a near-opening seed had valid gap values around 0.006770054281 meV but projected-gradient errors 4.88e-4, 2.02e-4 and 1.22e-3, above the 1e-4 gate. The reference run rejected the selected minimum's positive-curvature check. The original helper failed to attach those curvature values or the completed search to the exception; only the reason and traceback were saved. This is a diagnostic-retention limitation of the original helper, preserved rather than backfilled.

The diagnostic plan was frozen after those failures and before diagnosis. At each engine's fold-.001, starting from retained N6 minimum coordinates, one Newton step reduced gradient errors from about .0022 to below 6e-8. This was a diagnostic, not acceptance. It separately reproduced indefinite finite-difference curvature at 1e-4/5e-5: the reference smaller eigenvalues were about -46,230 and -13,718, with large asymmetry. At 1e-6/5e-7, both eigenvalues are positive and agree: the smaller is about 2094.5; the larger about 6.59 million. This supports under-resolution of a stiff avoided crossing, not a negative-curvature physical conclusion. Original failed curvature values remain unavailable.

The recovery plan was then frozen. It reruns both opening stations, each at both original interior/edge grids, and measures the previously unmeasured upper pair. It reuses the unchanged original fold/root/flat-pair charge prefix by exact hash and demands identical runtime identities. Original acceptance thresholds remain: gradient <=1e-4, positive gap >1e-5, positive curvature, value consistency <=1e-8, seed nonworsening <=1e-7 and mesh agreement <=.001 meV.

The changes are additional resolution: bounded Newton gradient polishing only after the three original optimizers fail their acceptance checks; curvature derivative steps 1e-6 and 5e-7; and new relative eigenvalue-agreement and symmetry gates of .001. Newton steps retain trace, Jacobian and line-search attempts, are capped at .001 in coordinate length, and cannot leave the chart. This is a separately declared recovery, not a retroactive change to the original plan. The recovery search helper preserves full partial search and curvature diagnostics if that gate rejects again.

The final reconciliation derives an ACCEPT_COMBINED_FIRST_ANN view only after the exact original rejection identity, accepted recovery identity, runtime equality, all prefix measurements, both new opening searches and upper-pair measurement pass. No original REJECT file is edited. The source/input/test/runtime-bound publication run is performed against this complete combined evidence. The summary reports original and recovery durations/hashes separately.

Limits persist: finite searches and mesh refinement do not prove a continuous interval or a complete global zero count. The upper SAME checkpoint does not independently prove continuous charge transfer. This recovery strengthens a numerical measurement; it is not physical-bilayer validation.
