# Frozen v055 lower unlink method

The scope is the separate lower remote/flat1 collision on T:0→−0.4 at A=0.2, B=−0.4, phi=0, ratio=0.8, eps=0.003, theta=1.05 degrees, lab_nn_full and constant tunnelling amplitudes. The gap index is 2 in the eight-band harness. BM retains linear reciprocal geometry (cutoff tolerance 1e−6); TBG retains exact reciprocal geometry (1e−9). Both corrected v054 engine sources are preserved byte-for-byte. This is one declared model with two engine implementations and a shared measurement harness.

Scope-selection pilots, not acceptance runs, continued both retained v044 step_028 lower roots to T=−0.31 in each N4 engine. Full-chart 12/18 seeded searches found positive lower gaps at −0.32 and −0.4. This selects a full-chart opening gate rather than a local-domain claim. The partner's −0.32 local box minimum is a different search and is not silently equated with our full-chart result.

PLAN.json freezes the execution, acceptance, reporting, packaging and test sources, method, baseline and input hashes before decisive execution. Fresh windows refuse an existing record. Every completed station is checkpointed; a failed window is REJECTED and retained. Both N4 cases must pass validation before either N6 case starts. At most two single-thread numerical workers run.

Fold location is bounded to [0,1]² and T∈[−0.4,0]. It requires converged two-component projected Hamiltonian, gap <1e−6 meV, rank-one spatial Jacobian with smallest singular value <1e−3 and largest >1, and exterior separation >1e−5 meV. Spatial differences at 2e−5/1e−5 must locate the parameter within 1e−6. Independent null-curvature and transverse-parameter derivatives at 2e−4/1e−4 must be nonzero, agree within 1%, and predict the pair on the T>fold side. Known quadratic, quartic and wrong-side normal forms test these diagnostics.

Nine bounded two-seed stations run from T=0 to fold+0.001. Each root has gap <1e−6, chart-boundary margin >0.005, pair separation >0.001 and individual step <0.06. The starting lower roots join the retained same-model/same-cutoff v044 inventory within 1e−6. This is a root join, not a historical lower-frame orientation join. The first and last station carry opposite unit charges under 256/512 same-radius loops and 512 half-radius loops, with 128/256 straight-path transport, external-gap minima and mesh-orientation checks. Radius is min(0.002,separation/8). Only unresolved phase steps permit the recorded 1024/2048/2048 fallback. Absolute charge is not carried through the annihilation. The other seven stations are root-continuation evidence, not charge measurements.

At fold−0.001 and T=−0.4, 18/24 full-chart searches use grid local minima, edge/corner seeds and the fold coordinate, followed by bounded gradient refinement. Both searches must find positive lower gaps >1e−5 meV, agree within 0.01 meV and improve their seeds. Separate one-dimensional searches along all four chart edges use 24/48 grids and bracketed refinement; their positive minima must agree within 0.01 meV. Coordinates are not silently wrapped at finite cutoff. These are finite numerical searches, not rigorous global bounds or exhaustive zero counts.

Flat roots are also refined at the nine root stations to record the lower nodes' offsets from their straight segment in the declared chart. This is sampled geometry only, without an interval no-crossing proof or a replacement for v044's accepted flat-pair frame replay.

The report revalidates raw measurements and requires complete-suite evidence bound to source/tests/results/anchors/environment. A count is derived from collected IDs, actual execution and JUnit. Hashes establish internal consistency, not independent authenticity. No physical-bilayer validation, named microscopic strain law for tunnelling, N→∞ extrapolation, complete CVE clearance or continuous-path theorem follows.
