# v061 bounded first-annihilation method

This describes the original frozen attempt below. Both initial runs were rejected at the opening stage. RECOVERY.md records the separately frozen resolution diagnosis and recovery that supplies the accepted opening and upper-pair witnesses; the original thresholds are preserved.

Freeze the numerical worker, helpers, engine adapters, engine sources and retained inputs before either N8 process starts. Run at most two numerical workers, one BLAS thread each. No imported Hamiltonian is modified. Both engines request lab_nn_full explicitly; the BM linear and reference exact reciprocal geometries and cutoff tolerances are retained.

The selected historical event has A=0, B=-0.4, phi=65 degrees, w0/w1=.8, theta=1.05 degrees and eps=.003. T goes from -.70 to -.74. Tunnelling is held constant (w1=110 meV, w0=88 meV). The flat gap is index 3 in the guarded eight-band sampler; the post-event upper gap is index 4. Finite-cutoff coordinates are never wrapped.

Root solves use bounded least squares on [0,1]^2, finite final success/status/message, residual and gap below 1e-6 meV, and chart margin above .005. Every seed is retained. Continued pairs must remain separated by .001 and jump less than .06; initial roots must be separated by .005. A duplicate or failed root is a rejection, never an annihilation verdict.

The fold solves two projected Hamiltonian components and a scaled Jacobian determinant. Derivative steps 2e-5 and 1e-5 must agree on T within 1e-6. Both results must succeed; gap and component residual remain below 1e-6, the smaller spatial singular value below 1e-3 and larger above 1, and adjacent-band isolation above 1e-5 meV. Independent finite differences at 2e-4 and 1e-4 check nonzero null curvature and transverse parameter slope, with signs predicting the observed pair side and 1% refinement agreement. This does not certify a continuous interval.

Eleven two-root states consist of nine regular states from -.70 to fold+.001 plus offsets .002 and .00025. Squared separation is compared with the fold coefficient at .002, .001, .00025 under a 2% gate. The retained N6 data already show roughly 2.1% corrections at offset .004075 and .5114% at .001. The nearer selected offsets are recorded before N8; the experiment is a local normal-form check, not a post-run fit or tolerance relaxation.

At -.70 and fold+.001, a bounded charge re-root must join the continued pair within 1e-6. Radius is min(.002,separation/8). At fixed T=-.74, an additional upper pair is bounded-refined from retained N6 seeds and uses radius .004. Every radius must be positive and smaller than one-third of pair separation. Spatial transport uses 128/256 base steps; every sampled local minimum of both exterior gaps is refined with final-result success, bracket, finite, nonworsening and isolation checks. Adaptive points near located minima support resolution, not a rigorous global bound. Transport overlap exceeds .1 and orientation determinant exceeds .99.

Each pair has three loop/radius trials at radii r,r,r/2 and meshes 256,512,512. Only the exact phase-step-resolution error allows one retry at 1024,2048,2048. Unit charge, loop closure, loop gap, phase steps and chart overlap are guarded by the retained independent_measurement module. Charges must agree across radius/mesh. The declared event requires OPPOSITE for the colliding flat pair and SAME for the surviving upper pair. Unexpected valid labels are retained in the rejected record rather than changed to meet the target. Absolute charge is not transported across the collision.

Post-event flat-gap stations are fold-.001 and fixed T=-.74. Each uses 18/24 inclusive square grids and 24/48 edge grids, explicit edge/corner seeds, and interior searches. L-BFGS-B, SLSQP and bounded Nelder-Mead fallbacks retain each final attempt's diagnostics. Accepted attempts require success, finite bounded coordinates, optimizer/re-evaluated value agreement <=1e-8, no worsening of their seed beyond 1e-7, and projected gradient <=1e-4. Selected minima require positive curvature at 1e-4 and 5e-5 steps. Both interior and boundary values must be >1e-5 meV and agree within .001 meV across the two resolutions. These are finite numerical searches, not a proof of no other zero anywhere.

The reconciler re-reads final metadata, root seed continuity, charges, loop/transport refinements, both opening searches, and exact historical anchors without recomputing any Hamiltonian. Publication requires a fresh complete-suite test artifact bound to all current source/test/result and runtime identities. The separate publication freeze is explicitly after the numerical run. All prior tracked files are preserved; the package uses their checked extracted tree, not a reconstructed claim about an old ZIP's byte stream.
