# v056 method and limits

The SOURCE_INDEX registry selects one canonical directory for each of eleven measurement batches. The claim catalog explicitly lists 20 record families and four engine/cutoff combinations. Auxiliary sensitivity experiments and every historical exploration are not certified by this map. The prior v053 preparation and v042 bridge/endpoint checkpoints are labeled as superseded or corroborating to avoid calling repetitions new coverage.

campaign_map.py reads JSON and hashes files. It imports no historical engine or report builder. Its selected checks include accepted saved status, engine/cutoff/protocol identity, station counts and sequence, selected frame diagnostics, root residual/index, fold derivative refinement and nondegeneracy fields, opposite pair charges with mesh/radius records, positive searched gaps, bounded-domain/boundary scope, per-band cycle signs, selected summary reconciliation, and coordinate/state joins. It compares checkpoint JSON with its case summary and hashes frames.npz as opaque bytes. Other summary fields and full numerical gate semantics are not independently re-evaluated.

The 44 joins compare two roots up to permutation in the recorded coordinate lift, without periodic remapping. All meet the preselected 1e-6 tolerance. They do not establish absolute frame orientation across versions. Nine joins per engine/cutoff use explicit stored states; the two braid-2 joins use ratio from the raw records and held parameters from reviewed v042 replay_second.py/models.State. Historical absent tunnelling fields are normalized only to the reviewed zero-kappa/average defaults. Initial fold roots are evaluated at definition.p, which need not equal pair_at.

Older first/upper/late folds recorded grid 18 at the near-open station and 18/24 farther away. Local extra-flat folds recorded 17/25 inside their explicit box and edge grids 24/48. Later lower folds use full-chart 18/24 searches. These differing scopes are exposed rather than silently promoted to a common refined/global certificate. Finite multi-start searches are not rigorous global bounds.

legacy_trace.py parses 343 selected top-level, engine-library and partner-script files. Its import and simple assigned callable aliases are flow-insensitive. It records source hashes, calls and success-field read contexts, without running source or proving reachability. It does not infer receiver types. The consumer findings are targeted source review layered on that inventory, not conclusions derived solely from matching method names. Full recursive historical call-graph and output attribution remain open.

legacy_impact.py is separate, authorized numerical execution. Before running it, the retained v041/v042 BM engine, historical gate/final_check/pair and harmonic helper were read. Their relevant definitions are loaded without executing old driver top-level bodies. The original pair body, including its success assertion, is preserved with an appended diagnostic return. The repaired variant replaces only BM.refine with the reviewed v055 implementation. Every SciPy optimization attempt is logged, along with returned and freshly recomputed values. Both models' static Hamiltonian bytes match for each recipe. The protocol was frozen before the two workers started. Runtime identity was not recorded independently inside each worker; use the declared session environment with that qualification.

The new tests exercise rejection of inconsistent/ambiguous/nonfinite JSON, wrong identities, missing frame/fold/charge/gap/cycle evidence, promoted local scope, mismatched helper probes, stale optimizer metadata in probe records, alias/context handling, invalid publication evidence, changed preserved files and unsafe/non-deterministic packaging. This is not measured execution coverage of the numerical engines. Earlier guard tests remain preserved with their own run evidence.

Publication re-builds the map, trace and comparison in memory and requires exact agreement with saved outputs. It verifies the frozen batch and prior tree, then publishes only a matching complete-suite test run. Hash agreement establishes internal consistency, not authenticity, chronology or scientific truth.

Scientific limits remain finite path sampling, shared harness/conceptual assumptions, N4/N6 cutoffs, a declared continuum model with constant tunnelling amplitudes, no microscopic strain law and no physical-bilayer validation. A named physical acceptance target and independent reference remain necessary before expanding claims.
